# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: ingress-nginx
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
